### PR TITLE
Facebook

### PR DESCRIPTION
**Pull request by myidsan**
facebook sharing feature added

### CODE REVIEW

**Comment by jameswhang** [comment]
FYI, PR is waaaaaaaaaay oversized... Try to keep PRs at reasonable sizes

**Comment by myidsan** [comment]
the PR size is big mostly because the previous PRs were not pulled. Are they good to go?

**Comment by jameswhang** [comment]
@myidsan Not sure if I get what you mean by "previous PRs were not pulled"... PR looks fine from a glance but we can't do thorough code reviews on ~700 lines of code change so plz keep them short next time :(

**Comment by myidsan** [comment]
I will keep them short in the future. Most of the changes are from deleting a whole page btw.
By previous PRs I meant the followings:
- https://github.com/nuvention-web/I-Front-2018/pull/14
- https://github.com/nuvention-web/I-Front-2018/pull/9
No reviewers gave me an okay for merge, so they have been piling up.

**Pull request merged**
